import Head from "next/head";
import dynamic from "next/dynamic";
const SwaggerUI = dynamic(import("swagger-ui-react"), { ssr: false });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="swagger-ui">
          <div className="wrapper">
            <form>
              <div className="parameter__name required">username</div>
              <div>
                <input type="text" />
              </div>
              <div className="parameter__name required">password</div>
              <div>
                <input type="text" />
              </div>
              <div>
                <button
                  className="btn"
                  onClick={() => {
                    alert("Hello!");
                  }}
                >
                  Login
                </button>
              </div>
            </form>
          </div>
        </div>
        <SwaggerUI
          requestInterceptor={(req) => {
            console.log({ req });
            return req;
          }}
          responseInterceptor={(resp) => {
            console.log({ resp });
            return resp;
          }}
          url="https://petstore.swagger.io/v2/swagger.json"
        />
      </main>
    </div>
  );
}
